version: 2
updates:
  # Python libraries
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

