name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t frame-it-cli:latest .

      - name: Run image
        run: docker run --rm frame-it-cli:latest --help
